### ISSUE TITLE
Cpp linter not working|

### ISSUE THREAD

**Issue by amrondonp** [JuezUN/linter-web-service#8]
![image](https://user-images.githubusercontent.com/6508705/37492928-28175f2e-2871-11e8-88a2-5cd0d671b5fb.png)

The oclint version installed is the one from mac-os
![image](https://user-images.githubusercontent.com/6508705/37492994-660c02e4-2871-11e8-9b39-9e5f50b815b5.png)

Gives the following errors

![image](https://user-images.githubusercontent.com/6508705/37492969-57f87142-2871-11e8-8148-bbfc90c31ded.png)

**Comment by larranaga** [comment]
solved in b3cba167741295a61fc6dd7810a949a5c8a76f4a
